## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.0.3
  - 1.1.0
notifications:
  email: false
git:
  depth: 99999999

## Allow failures on nightly julia
## (tests will run but not make your overall status red)
matrix:
  allow_failures:
  - julia: nightly

sudo: required

addons:
  apt: # apt-get for linux
    packages:
    - hdf5-tools
before_script: # homebrew for mac
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install hdf5; fi

## uncomment the following lines to override the default test script
#script:
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("MentaLiST"); Pkg.test("MentaLiST"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("MentaLiST")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("MentaLiST")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
