language: python
python:
  - "3.6"
os:
  - linux
sudo: required
notifications:
  email: false
git:
  depth: 99999999

install:
  - sudo apt-get update -qq
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda update -q -y conda
  - conda info -a
  - conda create -c bioconda -c conda-forge -q -y -n test-environment python=$TRAVIS_PYTHON_VERSION julia=0.5.2 hdf5 mpfr libxml2 unzip
  - source activate test-environment
  - julia -e 'Pkg.clone(pwd()); Pkg.build("MentaLiST")'

script: 
  - julia -e 'Pkg.test("MentaLiST"; coverage=true)'

after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("MentaLiST")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("MentaLiST")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
