name: mentalist
owner: dfornika
description: MLST caller designed to handle large typing schemes.
homepage_url: https://github.com/WGS-TB/MentaLiST
long_description: 
remote_repository_url: https://github.com/WGS-TB/MentaLiST/tree/mentalist_v0.2
type: unrestricted
