{% set name = "MentaLiST" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/WGS-TB/MentaLiST.git
  git_rev: v0.2.1
    
build:
  skip: True  # [osx]

requirements:
  build:
    - julia 0.6.1
    - hdf5
    - mpfr
    - libxml2
  run:
    - julia 0.6.1
    - hdf5
    - mpfr
    - libxml2

test:
  commands:
    - mentalist -h

about:
  home: https://github.com/WGS-TB/MentaLiST
  summary: The MLST pipeline developed by the PathOGiST research group.
  license: MIT
  license_file: LICENSE
