#!/usr/bin/env Rscript

args = commandArgs(trailingOnly=TRUE)

usage <- function() {
  cat("usage: mentalist_tree <input.tsv>\n")
}

main <- function(args) {
  if(is.na(args[1])){
    usage()
    return()
  }
  suppressMessages(library(phangorn))
  
  distance_matrix <- as.matrix(read.csv(args[1], row.names=1, sep="\t"))
  nj_tree <- NJ(distance_matrix)
  newick_tree <- write.tree(nj_tree)
  cat(newick_tree, '\n')
}

if(!interactive()) {
    main(args)
}
